apiVersion: v1
kind: ConfigMap
metadata:
  name: udcn-benchmark-baseline
  namespace: udcn-system
data:
  benchmark.yaml: |
    # Baseline Benchmark Configuration
    scenario:
      name: "baseline"
      description: "Baseline performance test with fixed client count"
      duration_sec: 300
      
    client:
      count: 20
      request_pattern: "poisson"
      concurrent_requests: 10
      timeout_ms: 5000
      
    workload:
      content_sizes:
        - size_bytes: 1024
          weight: 0.4
        - size_bytes: 102400
          weight: 0.4
        - size_bytes: 10485760
          weight: 0.2
      content_distribution: "zipf"
      zipf_alpha: 0.9
      content_catalog_size: 10000
      
    metrics:
      enabled: true
      report_interval_sec: 5
      detailed_histograms: true
      
    export:
      format: "csv"
      filename: "/results/baseline.csv"
