apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: udcn-istio-installation
spec:
  profile: default
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    pilot:
      enabled: true
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
    pilot:
      resources:
        requests:
          cpu: 500m
          memory: 2048Mi
        limits:
          cpu: 1000m
          memory: 4096Mi
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        autoscaleMin: 1
        autoscaleMax: 5
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: udcn-vs
  namespace: udcn-system
spec:
  hosts:
  - "*"
  gateways:
  - udcn-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: udcn-controller-service
        port:
          number: 5000
  - match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        host: udcn-controller-service
        port:
          number: 9092
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: udcn-gateway
  namespace: udcn-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: udcn-controller-destination
  namespace: udcn-system
spec:
  host: udcn-controller-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: udcn-external-services
  namespace: udcn-system
spec:
  hosts:
  - "*.github.com"
  - "*.googleapis.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
